version: '3.9'

services:
  db:
    image: postgres:15-alpine
    container_name: lesson7-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lesson7db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d lesson7db"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - lesson7-net

  app:
    build: .
    container_name: lesson7-app
    restart: unless-stopped
    ports:
      - "8010:8010"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - lesson7-net

networks:
  lesson7-net:
    driver: bridge
